# ฟ้าฝน — ตัวเฝ้าเรดาร์ส่งแจ้งเตือนฝน (Cloudflare Workers แผนฟรี)
name = "fafon-alert"
main = "src/index.ts"
compatibility_date = "2026-09-01"
workers_dev = true
preview_urls = false

# every 5 minutes
[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "SUBS"
id = "5f9bbee5dd984c9393bcce8a316d17ac"

[observability]
enabled = true
